# Customize Prometheus
prometheus:
  ingress:
    enabled: false
    hosts:
     - prometheus.apps.tkc01.lab.local
    path: "/*"
  service:
    type: LoadBalancer
  prometheusSpec:
    secrets:
    - etcd-client
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
#          storageClassName: wrkldmgmt-storage-policy
          resources:
            requests:
              storage: 20Gi

# Customize Grafana
grafana:
  # Set password for Grafana admin user
  adminPassword: VMware1!
  ingress:
    enabled: false
    hosts:
     - grafana.apps.tkc01.lab.local
    path: "/*"
  service:
    type: LoadBalancer
  persistence:
    enabled: true
#    storageClassName: wrkldmgmt-storage-policy
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
# Customize Alertmanager
alertmanager:
  ingress:
    enabled: false
    hosts:
     - alertmanager.apps.tkc01.lab.local
    path: "/*"
  service:
    type: LoadBalancer
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
#          storageClassName: wrkldmgmt-storage-policy
          resources:
            requests:
              storage: 10Gi
# Customer api-server
kubeApiServer:
  enabled: true
  tlsConfig:
    serverName: kubernetes
    insecureSkipVerify: true
# Customize etcd
kubeEtcd:
  service:
    port: 2379
    targetPort: 2379
    selector:
      component: etcd
  serviceMonitor:
    insecureSkipVerify: true
    scheme: https
    caFile: "/etc/prometheus/secrets/etcd-client/etcd-ca"
    certFile: "/etc/prometheus/secrets/etcd-client/etcd-client"
    keyFile: "/etc/prometheus/secrets/etcd-client/etcd-client-key"
# Customer core-dns
coreDns:
  enabled: true
  service:
    port: 9153
    targetPort: 9153
    selector:
      k8s-app: kube-dns
# Customer kubelet
kubelet:
  serviceMonitor:
    https: true
# Customize node-exporter
prometheus-node-exporter:
  hostNetwork: false
# Disable kube-controller-manager
kubeControllerManager:
  enabled: false
# Disable kube-scheduler
kubeScheduler:
  enabled: false
# Disable kube-proxy
kubeProxy:
  enabled: false


