apiVersion: v1
kind: ServiceAccount
metadata:
  name: vrealize-tkc01
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vrealize-tkc01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: vrealize-tkc01
    namespace: kube-system
