apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: minio-pv-claim
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: workload-mgmt # Change to your storageClassName
    resources:
        requests:
            storage: 10Gi
