kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: busybox-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: thin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
#  namespace: default
  annotations:
    backup.velero.io/backup-volumes: busybox-vol
spec:
  containers:
  - image: busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
#  restartPolicy: Always
    volumeMounts:
    - name: busybox-vol
      mountPath: /pvol
  volumes:
  - name: busybox-vol
    persistentVolumeClaim:
      claimName: busybox-pvc
