apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:custom-runasany-restricted
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp-custom-runasany-nonpriv
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:serviceaccounts-custom-psp
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:custom-runasany-restricted