apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-contraints
spec:
  containers:
  - name: ctr-resource-contraints
    image: nginx
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
        ephemeral-storage: "2Gi"
      requests:
        cpu: "500m"
        memory: "500Mi"
        ephemeral-storage: "1Gi"
