apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  name: psp-custom-runasany
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:psp-custom-runasany
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp-custom-runasany
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
#### Uncomment below and apply for enabling policy on entire cluster
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: psp:psp-custom-runasany
#subjects:
#- apiGroup: rbac.authorization.k8s.io
#  kind: Group
#  name: system:serviceaccounts
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: psp:psp-custom-runasany

